# fly.toml app configuration file generated for portfolio-9vdwiw on 2025-09-07T17:36:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-9vdwiw'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
source = "pb_data"
destination = "/app/release"
